### PR TITLE
Fix case-sensitivity issues

### PR DESCRIPTION
**Pull request by md-5**
See https://jira.codehaus.org/browse/PLX-458

### CODE REVIEW

**Comment by jvanzyl** [comment]
I do not use plexus-compiler anymore myself so it's not likely I will look at it.

**Comment by jvanzyl** [comment]
Other Maven committers generally keep up though.

**Comment by md-5** [comment]
Thanks for looking!

**Comment by jvanzyl** [comment]
If you're using the eclipse compiler you may actually want to look at the Takari Lifecycle which has modern support for JDT including proper access restriction and proper incremental compilation.

http://takari.io/book/40-lifecycle.html

**Comment by md-5** [comment]
That looks pretty cool. I'll take a look.

**Comment by md-5** [comment]
Takari is useless on OpenJDK, guess I'll deploy a custom version of this.
Thanks anyway.

**Comment by md-5** [comment]
Was this fixed?

**Comment by kellyrob99** [comment]
@md-5 No, the ownership of this plugin has moved to https://github.com/codehaus-plexus/plexus-compiler
We haven't supported this plugin directly for quite some time.

**Pull request closed without merging**
